version: '2.4'
services:
  bot:
    container_name: autotrader
    build: .
    restart: always
    volumes:
      - .:/code
    logging:
      driver: "json-file"
      options:
        max-size: "512m"
        max-file: "10"
    mem_limit: "768m"